[pytest]
testpaths = tests introduction practice-orders-processing/tests user-analytics-api/tests tdd-bddp-practise/tests practice-orders-processing/tests
pythonpath = . practice-orders-processing user-analytics-api document-editor tdd-bddp-practise practice-orders-processing
addopts = -v --color=yes --setup-show